services:
  db:
    image: postgres:16-alpine
    container_name: solutech-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: solutech
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: solutech-adminer
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:8080"

  redis:
    image: redis:7-alpine
    container_name: solutech-redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redisinsight:
    image: redis/redisinsight:latest
    container_name: solutech-redisinsight
    restart: unless-stopped
    depends_on:
      - redis
    ports:
      - "5540:5540"

volumes:
  postgres_data:
  redis_data:
